import "~/styles/globals.css";

import { Inter } from 'next/font/google';
import Navbar from "./_components/Navbar";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  weight: ["400", "700"],
  subsets: ["latin"]
});

export const metadata = {
  title: "muChat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <TRPCReactProvider>
          {<Navbar />}
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
