import "~/styles/globals.css";

import { Inter } from 'next/font/google';
import { TRPCReactProvider } from "~/trpc/react";
import NavbarToggle from "./_components/NavbarToggle";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  weight: ["400", "700"],
  subsets: ["latin"]
});

export const metadata = {
  title: "muChat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={inter.className}>
      <body className="flex min-h-[100vh] w-full
      flex-col overflow-scroll">
        <TRPCReactProvider>
          {<NavbarToggle />}
          {<Toaster />}
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
